#nome da pipeline
name : Run Testes- Scheduler

#momento de execução
on : 
  schedule:
    - cron: '0 20,22,23 * * 1-5'

jobs:
  #será feito na pipeline
  #apenas um job : rodar os testes
  cypress-run:
   #maquina que será executado
   runs-on: ubuntu-latest  

   #passo a passo para rodar os testes  
   steps:  
    #clone do projeto  
    - name: Checkout/Clone do projeto
      uses: actions/checkout@v4

    ##exemplo de execução terminal
    - name: Instalar dependências do projeto
      run: npm install

    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    # upload do relatorio do mocha
    - name: upload relatório 
      uses: actions/upload-pages-artifact@v3
      with:
        name: Relatório
        path: cypress/reports/html