#nome da pipeline
name : Run Testes

#momento de execução
on : 
  pull_request:
    branches: [master] 

jobs:
  #será feito na pipeline
  #apenas um job : rodar os testes
  cypress-run:
   #maquina que será executado
   runs-on: ubuntu-latest  

   #passo a passo para rodar os testes  
   steps:  
    #clone do projeto  
    - name: Checkout/Clone do projeto
      uses: actions/checkout@v3
    ##exemplo de execução terminal
    - name: instalar dependencias do projeto
      uses: npm install

    - name: Run tests
      uses: cypress-io/github-action@v5
      with:
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} 